import { type Metadata } from 'next';
import React from 'react';
import { AppProviders } from '@/common/components/AppProviders';
import { notoSansJP } from '@/common/fonts/font';
import '@/app/global.css';
import GlobalFooter from '@/common/components/layout/GlobalFooter';
import GlobalHeader from '@/common/components/layout/GlobalHeader';
import { MSWComponent } from '@/mocks/MSWComponent';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  return (
    <html lang="ja" className={notoSansJP.variable} suppressHydrationWarning>
      <body>
        {process.env.NODE_ENV === 'development' && <MSWComponent />}
        <AppProviders>
          <GlobalHeader />
          <main>{children}</main>
          <GlobalFooter />
        </AppProviders>
      </body>
    </html>
  );
}
